config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :videos, except: [:index]
  end

  resources :videos, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end


  devise_for :users
  resources :users, only: [:show]

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  post :incoming, to: 'incoming#create'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :videos, dependent: :destroy

  validates :title, length: { minimum: 3 }, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!, except: (:index)

  def index
    @topics = Topic.includes(:videos).all  # load all upfront for n+1 efficiency
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    if @topic.save
      flash[:notice] = "Your Topic has been saved"
      redirect_to @topic
    else
      flash.now[:alert] = "There was an error creating your topic -- Please try again"
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Your Topic has been updated"
      redirect_to @topic
    else
      flash.now[:alert] = "There was an error updating your topic -- Please try again"
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic

    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "There was an error deleting your topic.  Please try again."
      render :show
    end

  end

  private

  def topic_params
    params.required(:topic).permit(:title)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <p>Guidelines for topics</p>
    <ul>
      <li>Make it relevant.</li>
      <li>Make it at least 3 characters long.</li>
      <li>Use good penmanship.</li>
    </ul>
  </div>

  <%= form_for [topic] do |f| %>
    <div class= "form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter new Topic name" %>

      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<%= render partial: 'form', locals: { topic: @topic } %>

app/views/topics/index.html.erb
<h1>Topics</h1>

<!--topic list -->
<div class="row nav nav-tabs">
 <div class="col-md-12">
   <% @topics.each do |topic| %>
     <div class="media inline-block">
       <div class="media-heading">
         <h6><%= link_to topic.title, topic %>&nbsp; &nbsp; &nbsp;</h6>
       </div>
     </div>
   <% end %>
 </div>
</div>

 &nbsp;
 <div class="row">
  <div class="col-md-12">
    <% @topics.each do |topic| %>
      <div class="panel">

        <div class="panel-heading">
          <h4><%= link_to topic.title, topic %></h4>
        </div>
        <div class="panel-body">
          <div class="col-md-12 panel panel-info">
            &nbsp;
            <% topic.videos.each_slice(3) do |slice| %>
              <%= render partial: 'videos/slice', locals: {slice: slice} %>
            <% end %>
          </div>
        </div>

      </div>
    <% end %>
  </div>
</div>

<div class="col-md-4">
  <% if policy(Video.new).create? %>
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  <% else %>
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    <h6> (you must be signed in to create a new topic!) </h6>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render partial: 'form', locals: { topic: @topic } %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
 <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
 <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
 <div class="row">
   <div class="col-md-12">
     
     <div class="panel">
       <div class="panel-heading"
        <h4>Videos in this topic:</h4>
       </div>
       <div class="panel-body">
        <div class="col-md-12 panel panel-info">
          <% @topic.videos.each_slice(3) do |slice| %>
            &nbsp;
            <%= render partial: 'videos/slice', locals: {slice: slice} %>
          <% end %>
        </div>
       </div>

     </div>
   </div>
 </div>
 <%= link_to "Add Video", new_topic_video_path(@topic), class: 'btn btn-success' %>

 <div>
   <p>You can also submit new videos by email using the following format: </p>
   <ul style="list-style-type:none"
     <li><%= mail_to "videos@argus.today", 'videos@argus.today' %></li>
     <li> Subject:  [put the topic name]</li>
     <li> Body:     [put only the link]</li>
   </ui>
 </div>