config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :videos, except: [:index]
  end

  resources :videos, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end


  devise_for :users
  resources :users, only: [:show]

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  post :incoming, to: 'incoming#create'
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :topic
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save :get_video_id
  before_save :get_video_title

  # default_scope {order('created_at DESC') }
    default_scope {order('rank DESC') }


  def get_video_id
    regex = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/
    match = regex.match(url)
    if match && !match[1].blank?
      self.video_id = match[1]
    end
  end

  def get_video_title
    video = Yt::Video.new id: self.video_id
    title = video.title
    if title
      self.video_title = title
    end
  end

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_action :authenticate_user!, except: (:show)

  def show
    @video = Video.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @video = Video.new
    authorize @video
  end

  def edit
    @video = Video.find(params[:id])
    @topic = @video.topic
    authorize @video
  end

  def create
    @video = Video.new(video_params)

    @topic = Topic.find(params[:topic_id])
    @video.topic = @topic
    @video.user = current_user

    authorize @video

    if @video.save
      flash[:notice] = "Video has been saved"
      redirect_to @video.topic
    else
      flash.now[:alert] = "There was an error creating the video -- Please try again"
      render :new
    end
  end

  def update
    @video = Video.find(params[:id])
    # @video.url = params[:video][:url]
    @video.assign_attributes(video_params)
    authorize @video

    if @video.save
      flash[:notice] = "The Video has been updated"
      redirect_to @video.topic
    else
      flash.now[:alert] = "There was an error updating the video -- Please try again"
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])
    authorize @video

    if @video.destroy
      flash[:notice] = "\"#{@video.video_id}\" was deleted successfully."
      redirect_to @video.topic
    else
      flash.now[:alert] = "There was an error deleting the video.  Please try again."
      render :show
    end

  end

  private

  def video_params
    params.required(:video).permit(:url, :topic_id)
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for [topic, video] do |f| %>
      <div class="form-group">
        <%= f.label "Video link" %>
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter YouTube video URL" %>
      </div>

<!--BUG  works fine for edit view, but new view, dropdown not function (starts blank, only can assign to current topic) -->
<!--possible fix: don't give topic dropdown if new vid  e.g. auto assign current topic  -->

      <div class-"form-group">
        <%= f.label :topic, "Topic" %>
        <%= f.collection_select :topic_id, Topic.order(:id), :id, :title, include_blank: true %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/videos/_slice.html.erb
<div class="row vid-row">
  <% slice.each do |video| %>
    <div class="col-sm-4">
      <ul class="text-center" style="list-style-type:none">
        <li>  <%= link_to video.video_title, topic_video_path(video.topic, video) %></li>
        <li> <%= link_to image_tag("http://img.youtube.com/vi/#{video.video_id}/2.jpg"), topic_video_path(video.topic, video) %></li>
        <li>
          <span>
            <%= render partial: 'votes/voting', locals: { video: video } %>
          </span>
        </li>
      </ul>
    </div>
  <% end %>
</div>

app/views/videos/edit.html.erb
<h1>Edit Video</h1>

<h4>Topic: <%= @video.topic.title %></h4>
<h4><%= @video.video_title %></h4>

<br><br>

<%= render partial: 'form', locals: { topic: @topic, video: @video } %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render partial: 'form', locals: { topic: @topic, video: @video } %>

app/views/videos/show.html.erb
<div>

  <h1><%= @video.video_title %></h1>
  <small>
    In topic: <%= link_to @video.topic.title, @video.topic %><br>
    submitted <%= time_ago_in_words(@video.created_at) %> ago.
  </small>
</div>


<div class="row">
  <div class="col-sm-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe src='https://www.youtube.com/embed/<%= @video.video_id %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' width='560' height='315' frameborder='0' allowfullscreen></iframe>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="row">
      <div class="col-sm-12">
        <% if policy(Video.new).create? %>
          <%= link_to "Delete Video", [@video.topic, @video], method: :delete, class: 'btn btn-danger' %>
          <%= link_to "Edit Video", edit_topic_video_path(@video.topic, @video), class: 'btn btn-success' %>
        <% else %>
          <%= link_to "Delete Video", '', class: 'btn btn-danger disabled', disabled:true %>
          <%= link_to "Edit Video", '', class: 'btn btn-success disabled', disabled:true %>
          <h6> You can only edit your own videos.  You  must be signed in to comment, vote or favorite!</h6>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">

        <% if current_user %>
          <%= render partial: 'favorites/favorite', locals: { video: @video } %>
        <% end %>

        <h5>
          <%= pluralize(@video.points, 'point') %>
          <div>
            <small>
              <%= pluralize(@video.up_votes, 'up vote') %>,
              <%= pluralize(@video.down_votes, 'down vote') %>
            </small>
          </div>
        </h5>
      </div>
    </div>

  <%= render partial: 'votes/voting', locals: { video: @video } %>

  </div>
</div>

<div>
  <h3>Comments:</h3>
  <%= render @video.comments %>
</div>

<% if policy(Comment.new).create? %>
  <%= render 'comments/form', comment: Comment.new, video: @video %>
<% end %>