config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :videos, except: [:index]
  end

  resources :videos, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end


  devise_for :users
  resources :users, only: [:show]

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  post :incoming, to: 'incoming#create'
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :video
  after_save :update_video

  validates :value, inclusion: { in: [-1,1], message: "%{value] is not a valid vote."}, presence: true

  private

  def update_video
    video.update_rank
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    before_action :authenticate_user!

    def up_vote
      update_vote(1)
      redirect_back(fallback_location: :root)
    end

    def down_vote
      update_vote(-1)
      redirect_back(fallback_location: :root)
    end

    private
    def update_vote(new_value)
      @video = Video.find(params[:video_id])
      @vote = @video.votes.where(user_id: current_user.id).first
      if @vote
        @vote.update_attribute(:value, new_value)
      else
        @vote = current_user.votes.create(value: new_value, video: @video)
      end
    end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_voting.html.erb
<% if current_user %>
<div class="vote-arrows">
  <span><%= link_to " ", video_up_vote_path(video), class: 'glyphicon glyphicon-thumbs-up', method: :post%></span>
  <span><strong><%= video.points %></strong></span>
  <span><%= link_to " ", video_down_vote_path(video), class: 'glyphicon glyphicon-thumbs-down', method: :post%></span>

   <!-- &nbsp  -->

   <% if current_user %>
     <%= render partial: 'favorites/favorite', locals: { video: video } %>
   <% end %>


  <!-- hold for favorite star?  or put favs in separate partial
  fav &nbsp -->
</div>
<% end %>